# Generated by Django 3.2.8 on 2021-11-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
